# global:
#   scrape_interval: 1m

# scrape_configs:
#   - job_name: "python_app"
#     metrics_path: /metrics/
#     static_configs:
#       - targets: ["aliexpress_api:9090"]

global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "python_app"
    metrics_path: /metrics/
    static_configs:
      - targets: ["api:8000"] # <--- Must match the service name in Docker Compose
